name: "Build and Push"

inputs:
  VERSION_MAJOR:
    required: true
  DATE_STAMP:
    required: true
  IMAGE_REGISTRY:
    required: true
  REGISTRY_USER:
    required: true
  REGISTRY_PASSWORD:
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare environment
      shell: bash
      run: |
        echo "VARIANT=--platform ${{ env.PLATFORM }}" >> "$GITHUB_ENV"

        # quay.io/almalinuxorg/almalinux-bootc
        IMAGE_DEST=${{ inputs.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
        echo "IMAGE_DEST=${IMAGE_DEST}" >> "$GITHUB_ENV"

        ARCH=${{ matrix.ARCH }}
        echo "CLEAN_ARCH=${ARCH//\//_}" >> "$GITHUB_ENV"

    - name: Build image
      id: build
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      shell: bash
      run: |
        BUILD_TIME=$(date -Iseconds)

        # define a multiline variable with heredoc
        LABELS=$(cat <<EOF
        redhat.id=${{ steps.info.outputs.id }}
        redhat.version-id=${{ steps.info.outputs.version-id }}
        version=${{ steps.info.outputs.version-id }}
        release=${{ steps.info.outputs.version-id }}
        build-date=${BUILD_TIME}
        org.opencontainers.image.created=${BUILD_TIME}
        org.opencontainers.image.version=${{ steps.info.outputs.long-version }}
        org.opencontainers.image.source=${{ github.repositoryUrl }}
        org.opencontainers.image.title=${{ env.IMAGE_NAME }}
        org.opencontainers.image.url=${{ github.event.repository.html_url }}
        EOF
        )

        while IFS= read -r label; do
          ALL_LABELS="$ALL_LABELS --label=\"$label\" --annotation=\"$label\""
        done <<< "$LABELS"

        sudo make image \
          PLATFORM=${{ env.PLATFORM }} \
          LABELS="${ALL_LABELS}" \
          IMAGE_NAME=${{ env.IMAGE_NAME }} \
          VERSION_MAJOR=${{ inputs.VERSION_MAJOR }}

        echo "image-id=$(cat /tmp/image-id)" >> $GITHUB_OUTPUT

    - name: rechunk image
      id: rechunk
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      shell: bash
      run: |
        make rechunk \
          PLATFORM=${{ env.PLATFORM }} \
          IMAGE_NAME=${{ env.IMAGE_NAME }}

        echo "image-id=sha256:$(sudo podman image inspect ${{ env.IMAGE_NAME }} -f "{{.Id}}")" >> $GITHUB_OUTPUT

    - name: Run Image
      id: run
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      shell: bash
      env:
        IMAGE_ID: ${{ steps.rechunk.outputs.image-id }}
      run: |
        sudo podman run ${{ env.VARIANT }} --rm -ti ${{ env.IMAGE_ID }} bootc --version

        INFO=$(sudo podman run ${{ env.VARIANT }} --rm ${{ env.IMAGE_ID }} bash -c "rpm -q almalinux-gpg-keys && cat /etc/os-release")
        echo "$INFO"

        echo "id=$(echo "$INFO" | grep "^ID=" | cut -d'=' -f2 | tr -d '"')" >> $GITHUB_OUTPUT
        echo "version-id=$(echo "$INFO" | grep "^VERSION_ID=" | cut -d'=' -f2 | tr -d '"')" >> $GITHUB_OUTPUT
        echo "long-version=$(echo "$INFO" | grep "^VERSION_ID=" | cut -d'=' -f2 | tr -d '"').${{ inputs.DATE_STAMP }}.0" >> $GITHUB_OUTPUT
        echo "vendor=$(echo "$INFO" | grep "^VENDOR_NAME=" | cut -d'=' -f2 | tr -d '"')" >> $GITHUB_OUTPUT

    - name: Push to registry
      id: push
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      env:
        IMAGE_ID: ${{ steps.rechunk.outputs.image-id }}
        VERSION: ${{ steps.run.outputs.version-id }}
      shell: bash
      run: |
        # The push fails for unknown reasons sometimes, so we'll retry it a few times
        for i in {1..5}; do
          sudo podman push --digestfile=/tmp/digestfile ${{ env.IMAGE_ID }} \
            docker://${IMAGE_DEST}:${{ env.VERSION }}-${{ inputs.DATE_STAMP }}-${{ env.CLEAN_ARCH }} && break || sleep $((10*i))
        done
        [ -f /tmp/digestfile ] || exit 1
        echo "digest=$(cat /tmp/digestfile)" >> $GITHUB_OUTPUT
        sudo podman inspect ${{ env.IMAGE_ID }}

    - name: Create Job Outputs
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      shell: bash
      run: |
        mkdir -p /tmp/outputs/digests

        jq -n --arg platform "${{ matrix.ARCH }}" \
          --arg major "${{ inputs.VERSION_MAJOR }}" \
          --arg digest "${{ steps.push.outputs.digest }}" \
          --arg id "${{ steps.run.outputs.id }}" \
          --arg version "${{ steps.run.outputs.version-id }}" \
          --arg long_version "${{ steps.run.outputs.long-version }}" \
          --arg vendor "${{ steps.run.outputs.vendor }}" \
          --arg image_id "${{ steps.rechunk.outputs.image-id }}" \
          '{($platform): {digest: $digest, id: $id, version: $version, major: $major, long_version: $long_version, vendor: $vendor, image_id: $image_id}}' \
          > /tmp/outputs/digests/${{ env.IMAGE_NAME }}_${{ matrix.VERSION_MAJOR }}_${{ env.CLEAN_ARCH }}.json

        cat /tmp/outputs/digests/${{ env.IMAGE_NAME }}_${{ matrix.VERSION_MAJOR }}_${{ env.CLEAN_ARCH }}.json

    - name: Upload Output Artifacts
      if: ${{ env.res != 0 || github.event_name == 'workflow_dispatch' }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: ${{ env.IMAGE_NAME }}_${{ matrix.VERSION_MAJOR }}_${{ env.CLEAN_ARCH }}
        retention-days: 1
        if-no-files-found: error
        path: |
          /tmp/outputs/digests/*.json
