images:
  almalinux-10-x64:
    platform: "linux"
    arch: "x64"
    owner: "764336703387"
    name: "AlmaLinux OS 10*x86_64"
    # ami: "ami-06be7a8dff9965741"
    preinstall: |
      dnf install jq tar wget /usr/bin/shasum -y

  ubuntu22-full-arm64-python3.7-3.13:
    platform: "linux"
    arch: "arm64"
    owner: "408085265505"
    ami: "ami-09b72f1a95ff33179"

  custom_x64_image:
    platform: "linux"
    arch: "x64"
    owner: "099720109477" # Official Ubuntu owner
    name: "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" # Official Ubuntu image
