images:
  almalinux_10_x86_64:
    platform: "linux"
    arch: "x64"
    owner: "764336703387"
    name: "AlmaLinux OS 10*"

  custom_x64_image:
    platform: "linux"
    arch: "x64"
    owner: "099720109477" # Official Ubuntu owner
    name: "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" # Official Ubuntu image
